spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    op en-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true #httpmethod관련, put/delete
translation:
  url:
    pusan: http://roman.cs.pusan.ac.kr/result_all.aspx?input=
    naver: https://dict.naver.com/name-to-roman/translation/?query=
    naver_address: https://search.naver.com/search.naver?where=nexearch&ie=utf8&X_CSA=address_search&query=
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
